### ISSUE TITLE
Files delimited by CRLF cause lex errors

### ISSUE THREAD

**Issue by StealthHydra179** [Bigjango13/Burlap#2]
![image](https://github.com/Bigjango13/Burlap/assets/47306082/82b614ec-d0ef-4380-9f34-cf345e562ed9)

### Current Behaviour:
Burlap Errors

### Expected Behaviour:
Newlines are ignored and "hi" is printed

### How to replicate:
paste
```

print( "hi" );
```
into a new sack file and run burlap `burlap main.sk`

### Burlap version: 
v1.2.5

**Comment by StealthHydra179** [comment]
![image](https://github.com/Bigjango13/Burlap/assets/47306082/552f1141-c3f5-4ba3-8cd5-681d7e2d2419)

Running the example sack code at the bottom of the README file in the sack repository yields this error

**Comment by StealthHydra179** [comment]
Issue can be resolved by switching from CRLF delimiters to LF delimiters.

**Comment by Bigjango13** [comment]
Should be fixed in 0b06ed7.
